import { WorldConfig } from "./types";

function makeVisual(icon: string, values: number[], accent?: string) {
  return { icon, values, accent };
}

export const worlds: WorldConfig[] = [
  {
    multiplier: 2,
    title: "Долина пар",
    subtitle: "Все предметы приходят по двое",
    biome: "Пары и двойники",
    teacherIntro:
      "Здесь все любят ходить парами. Если видишь один предмет, представь рядом его двойника.",
    teacherTip: "Умножить на 2 значит удвоить число.",
    accent: "#4dd8ff",
    accentSoft: "#d9fbff",
    accentStrong: "#0f7fa3",
    background: "linear-gradient(180deg, #e5fdff 0%, #b0f2ff 48%, #67cbe5 100%)",
    badge: "×2",
    scenery: ["twins", "blocks"],
    learnCards: [
      {
        title: "Удвоение",
        text: "Один кубик становится двумя такими же.",
        hint: "2 × 4 это 4 и ещё 4.",
        visual: [makeVisual("■", [1, 1]), makeVisual("■", [4, 4], "#4dd8ff")],
      },
      {
        title: "Считаем парами",
        text: "Можно прыгать по числовой дорожке: 2, 4, 6, 8.",
        hint: "Каждый шаг добавляет ещё 2.",
        visual: [makeVisual("●", [2, 4, 6, 8])],
      },
      {
        title: "Найди удвоение",
        text: "Что получится, если удвоить 3?",
        hint: "Сначала подумай, потом нажми ответ.",
        visual: [makeVisual("◆", [3, 3])],
        interaction: {
          type: "choice",
          prompt: "2 × 3 = ?",
          options: [5, 6, 8],
          correct: 6,
          successText: "Верно! Три да три равно шесть.",
        },
      },
      {
        title: "Двойники рядом",
        text: "У каждой зверушки есть пара. Это удобно считать.",
        hint: "2 × 5 это 5 + 5.",
        visual: [makeVisual("🐾", [5, 5])],
      },
      {
        title: "Секрет долины",
        text: "Четные числа особенно дружат с умножением на 2.",
        hint: "Открой подсказку, чтобы запомнить правило.",
        visual: [makeVisual("✦", [2, 4, 6, 8, 10])],
        interaction: {
          type: "reveal",
          prompt: "Почему ответы идут через одно число?",
          answer: "Потому что каждый раз мы добавляем ещё одну пару, то есть ещё 2.",
          buttonLabel: "Открыть секрет",
        },
      },
    ],
    warmupFactors: [2, 4],
    quizFactors: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    multiplier: 3,
    title: "Острова троек",
    subtitle: "Три острова в каждом архипелаге",
    biome: "Острова",
    teacherIntro:
      "На этих островах все собирается по три. Если увидеть три одинаковых группы, ответ находится быстро.",
    teacherTip: "Умножить на 3 значит взять три одинаковые группы.",
    accent: "#ff9f43",
    accentSoft: "#fff0dc",
    accentStrong: "#c66a1c",
    background: "linear-gradient(180deg, #fff6cf 0%, #ffd37f 44%, #ff9645 100%)",
    badge: "×3",
    scenery: ["islands", "waves"],
    learnCards: [
      {
        title: "Три группы",
        text: "3 × 2 это три группы по 2.",
        hint: "2 + 2 + 2 = 6.",
        visual: [makeVisual("⬢", [2, 2, 2], "#ff9f43")],
      },
      {
        title: "Шаги по волнам",
        text: "Считай через 3: 3, 6, 9, 12.",
        hint: "Каждая волна приносит ещё 3.",
        visual: [makeVisual("≈", [3, 6, 9, 12])],
      },
      {
        title: "Выбери берег",
        text: "Сколько будет 3 × 4?",
        hint: "Представь четыре тройки.",
        visual: [makeVisual("▣", [3, 3, 3, 3])],
        interaction: {
          type: "choice",
          prompt: "3 × 4 = ?",
          options: [10, 12, 14],
          correct: 12,
          successText: "Точно! Четыре тройки дают двенадцать.",
        },
      },
      {
        title: "Треугольный след",
        text: "Тройки удобно видеть как маленькие треугольники.",
        hint: "1 + 2 можно быстро заметить глазом.",
        visual: [makeVisual("▲", [3, 6, 9])],
      },
      {
        title: "Правило островов",
        text: "Когда видишь три одинаковых островка, просто сложи их.",
        hint: "Подсказка напомнит способ.",
        visual: [makeVisual("☼", [3, 3, 3])],
        interaction: {
          type: "reveal",
          prompt: "Как проверить ответ?",
          answer: "Можно заменить умножение сложением: 3 × 5 это 5 + 5 + 5.",
          buttonLabel: "Показать способ",
        },
      },
    ],
    warmupFactors: [2, 3],
    quizFactors: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {
    multiplier: 4,
    title: "Квадро-город",
    subtitle: "Улицы из квадратов и блоков",
    biome: "Квадраты и город",
    teacherIntro:
      "В этом городе все строится квадратами. Четыре удобно видеть как два раза по два.",
    teacherTip: "Умножить на 4 можно как удвоить и ещё раз удвоить.",
    accent: "#f76f8e",
    accentSoft: "#ffe3ea",
    accentStrong: "#be3657",
    background: "linear-gradient(180deg, #ffe5f0 0%, #ffb7ca 45%, #ff7f9b 100%)",
    badge: "×4",
    scenery: ["city", "grid"],
    learnCards: [
      {
        title: "Два раза по два",
        text: "4 это 2 и ещё 2.",
        hint: "Сначала удвой, потом снова удвой.",
        visual: [makeVisual("▦", [2, 2]), makeVisual("▦", [2, 2], "#f76f8e")],
      },
      {
        title: "Квадратный шаг",
        text: "Числа идут так: 4, 8, 12, 16.",
        hint: "Каждый новый домик добавляет ещё 4.",
        visual: [makeVisual("□", [4, 8, 12, 16])],
      },
      {
        title: "Выбери этаж",
        text: "Сколько окон в 4 рядах по 3?",
        hint: "Можно посчитать как 3 + 3 + 3 + 3.",
        visual: [makeVisual("▥", [3, 3, 3, 3])],
        interaction: {
          type: "choice",
          prompt: "4 × 3 = ?",
          options: [10, 12, 16],
          correct: 12,
          successText: "Да! Четыре тройки это двенадцать.",
        },
      },
      {
        title: "Городская сетка",
        text: "Квадраты помогают не потеряться и видеть группы.",
        hint: "4 × 5 можно увидеть как 20 клеток.",
        visual: [makeVisual("▣", [4, 4, 4, 4, 4])],
      },
      {
        title: "Архитекторская подсказка",
        text: "Запомни: 4 это удвоенная двойка.",
        hint: "Открой правило.",
        visual: [makeVisual("✸", [4, 8, 12])],
        interaction: {
          type: "reveal",
          prompt: "Как быстро считать ×4?",
          answer: "Сначала умножь на 2, а потом ещё раз на 2. Например, 4 × 6: 6 → 12 → 24.",
          buttonLabel: "Показать правило",
        },
      },
    ],
    warmupFactors: [2, 5],
    quizFactors: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {
    multiplier: 5,
    title: "Экспресс пятёрок",
    subtitle: "Станции, вагоны и точные остановки",
    biome: "Поезд и станции",
    teacherIntro:
      "Паровоз пятёрок идёт очень ровно: ответы заканчиваются на 0 или 5. Это отличный короткий путь.",
    teacherTip: "У ответов на ×5 почти всегда на хвостике 0 или 5.",
    accent: "#ffd166",
    accentSoft: "#fff4d7",
    accentStrong: "#bf8d12",
    background: "linear-gradient(180deg, #fff8db 0%, #ffe38c 42%, #ffbe3b 100%)",
    badge: "×5",
    scenery: ["train", "smoke"],
    learnCards: [
      {
        title: "Станции через 5",
        text: "Поезд останавливается так: 5, 10, 15, 20.",
        hint: "Каждая станция дальше ещё на 5.",
        visual: [makeVisual("▬", [5, 10, 15, 20], "#ffd166")],
      },
      {
        title: "Хвостик ответа",
        text: "У ответов на ×5 конец числа это 0 или 5.",
        hint: "Посмотри на ряд чисел.",
        visual: [makeVisual("◌", [5, 10, 15, 20, 25])],
      },
      {
        title: "Билет на поезд",
        text: "Какой ответ подходит к 5 × 6?",
        hint: "Станции растут по пять.",
        visual: [makeVisual("▭", [5, 5, 5, 5, 5, 5])],
        interaction: {
          type: "choice",
          prompt: "5 × 6 = ?",
          options: [25, 30, 35],
          correct: 30,
          successText: "Верно! Шестая станция это 30.",
        },
      },
      {
        title: "Ладошка помогает",
        text: "Пять пальцев на руке тоже подсказывают ответы.",
        hint: "Две руки это уже 10.",
        visual: [makeVisual("✋", [5, 5, 10])],
      },
      {
        title: "Секрет машиниста",
        text: "Если число чётное, ответ часто кончается на 0. Если нечётное, на 5.",
        hint: "Подсказка внутри.",
        visual: [makeVisual("✦", [10, 15, 20, 25])],
        interaction: {
          type: "reveal",
          prompt: "Как быстро понять последнюю цифру?",
          answer: "У 5 × 2, 5 × 4, 5 × 6 ответ оканчивается на 0. У 5 × 1, 5 × 3, 5 × 5 на 5.",
          buttonLabel: "Открыть подсказку",
        },
      },
    ],
    warmupFactors: [1, 4],
    quizFactors: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    multiplier: 6,
    title: "Подводный риф",
    subtitle: "Ряды кораллов и морские группы",
    biome: "Подводный мир",
    teacherIntro:
      "Под водой шестерки складываются в красивые кораллы. Здесь удобно видеть две тройки или три двойки.",
    teacherTip: "6 можно представить как 3 + 3 или 2 + 2 + 2.",
    accent: "#38bdf8",
    accentSoft: "#dff5ff",
    accentStrong: "#157da8",
    background: "linear-gradient(180deg, #e4fbff 0%, #91e6ff 40%, #1fb4d9 100%)",
    badge: "×6",
    scenery: ["reef", "bubbles"],
    learnCards: [
      {
        title: "Шесть кораллов",
        text: "6 × 2 это две шестерки.",
        hint: "6 + 6 = 12.",
        visual: [makeVisual("✺", [6, 6], "#38bdf8")],
      },
      {
        title: "Две тройки",
        text: "Каждую шестерку можно разделить на две тройки.",
        hint: "Иногда так считать легче.",
        visual: [makeVisual("◍", [3, 3]), makeVisual("◍", [3, 3])],
      },
      {
        title: "Выбери жемчужину",
        text: "Сколько будет 6 × 4?",
        hint: "Это 6 + 6 + 6 + 6.",
        visual: [makeVisual("◉", [6, 6, 6, 6])],
        interaction: {
          type: "choice",
          prompt: "6 × 4 = ?",
          options: [20, 24, 26],
          correct: 24,
          successText: "Отлично! Четыре шестерки это двадцать четыре.",
        },
      },
      {
        title: "Подводный ряд",
        text: "Числа на дорожке: 6, 12, 18, 24.",
        hint: "Каждый пузырек добавляет ещё 6.",
        visual: [makeVisual("○", [6, 12, 18, 24])],
      },
      {
        title: "Морской совет",
        text: "Если трудно, разбей 6 на 5 и 1 или на 3 и 3.",
        hint: "Подсказка поможет.",
        visual: [makeVisual("✧", [6, 12, 18])],
        interaction: {
          type: "reveal",
          prompt: "Как упростить 6 × 7?",
          answer: "Можно сделать 5 × 7 и добавить ещё 7: 35 + 7 = 42.",
          buttonLabel: "Показать приём",
        },
      },
    ],
    warmupFactors: [2, 3],
    quizFactors: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    multiplier: 7,
    title: "Космо-семёрка",
    subtitle: "Планеты и орбиты далёких чисел",
    biome: "Космос",
    teacherIntro:
      "Семёрки живут в космосе и любят точность. Их не всегда видно сразу, зато можно искать ритм и опоры.",
    teacherTip: "7 удобно учить как особую цепочку: 7, 14, 21, 28...",
    accent: "#8b5cf6",
    accentSoft: "#efe8ff",
    accentStrong: "#5b34bf",
    background: "linear-gradient(180deg, #1c1642 0%, #3d2f7f 45%, #8360ff 100%)",
    badge: "×7",
    scenery: ["stars", "planets"],
    learnCards: [
      {
        title: "Орбиты семёрок",
        text: "Семёрки летят так: 7, 14, 21, 28.",
        hint: "Запомни ритм чисел.",
        visual: [makeVisual("✦", [7, 14, 21, 28], "#b9a7ff")],
      },
      {
        title: "Опора на 5 и 2",
        text: "7 это 5 и ещё 2. Иногда так считать проще.",
        hint: "Например, 7 × 3 это 5 × 3 и ещё 2 × 3.",
        visual: [makeVisual("⬤", [5, 2]), makeVisual("⬤", [5, 2], "#8b5cf6")],
      },
      {
        title: "Планета ответа",
        text: "Какой ответ у 7 × 5?",
        hint: "Сначала представь 5 семёрок.",
        visual: [makeVisual("☄", [7, 7, 7, 7, 7])],
        interaction: {
          type: "choice",
          prompt: "7 × 5 = ?",
          options: [30, 35, 40],
          correct: 35,
          successText: "Супер! Пять семёрок это тридцать пять.",
        },
      },
      {
        title: "Звёздная дорожка",
        text: "У семёрок есть заметный ритм, его нужно потренировать.",
        hint: "Повтори ряд вслух.",
        visual: [makeVisual("✧", [7, 14, 21, 28, 35])],
      },
      {
        title: "Космический лайфхак",
        text: "Сложные ответы можно собирать из знакомых: 5× и 2×.",
        hint: "Открой пример.",
        visual: [makeVisual("✺", [35, 14])],
        interaction: {
          type: "reveal",
          prompt: "Как посчитать 7 × 7?",
          answer: "Сделай 5 × 7 = 35 и 2 × 7 = 14. Потом сложи: 35 + 14 = 49.",
          buttonLabel: "Показать пример",
        },
      },
    ],
    warmupFactors: [2, 5],
    quizFactors: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    multiplier: 8,
    title: "Джунгли восьмёрок",
    subtitle: "Лианы, ступени и ритм силы",
    biome: "Джунгли",
    teacherIntro:
      "В джунглях восьмерки растут быстро. Их удобно видеть как удвоенную четверку или четыре пары.",
    teacherTip: "8 можно считать как 4 и ещё 4, а 4 это два раза по два.",
    accent: "#22c55e",
    accentSoft: "#defce8",
    accentStrong: "#157a3a",
    background: "linear-gradient(180deg, #e9ffe5 0%, #92e88d 38%, #2eb872 100%)",
    badge: "×8",
    scenery: ["jungle", "leaves"],
    learnCards: [
      {
        title: "Восьмёрка из четверок",
        text: "8 это 4 и ещё 4.",
        hint: "Поэтому можно считать через удвоение.",
        visual: [makeVisual("❖", [4, 4], "#22c55e")],
      },
      {
        title: "Лианы чисел",
        text: "Ряд идёт так: 8, 16, 24, 32.",
        hint: "Каждая лиана добавляет ещё 8.",
        visual: [makeVisual("〰", [8, 16, 24, 32])],
      },
      {
        title: "Выбери тропу",
        text: "Сколько будет 8 × 3?",
        hint: "Три восьмёрки легко сложить.",
        visual: [makeVisual("⬣", [8, 8, 8])],
        interaction: {
          type: "choice",
          prompt: "8 × 3 = ?",
          options: [16, 24, 28],
          correct: 24,
          successText: "Верно! Три восьмерки это двадцать четыре.",
        },
      },
      {
        title: "Четыре пары",
        text: "8 это ещё и четыре пары.",
        hint: "Иногда пары видны лучше, чем вся восьмерка.",
        visual: [makeVisual("◈", [2, 2, 2, 2])],
      },
      {
        title: "Совет проводника",
        text: "Если знаешь ×4, то ×8 это просто в два раза больше.",
        hint: "Подсказка внутри.",
        visual: [makeVisual("✶", [8, 16, 24])],
        interaction: {
          type: "reveal",
          prompt: "Как посчитать 8 × 6?",
          answer: "Сначала 4 × 6 = 24, потом удвой: 24 + 24 = 48.",
          buttonLabel: "Открыть способ",
        },
      },
    ],
    warmupFactors: [1, 2],
    quizFactors: [1, 2, 3, 4, 5, 6, 7, 8],
  },
  {
    multiplier: 9,
    title: "Башня девяток",
    subtitle: "Высокие этажи и мудрые ступени",
    biome: "Башня",
    teacherIntro:
      "Башня девяток высокая, но очень логичная. Девятка почти как десятка, только на один меньше.",
    teacherTip: "9 × n это 10 × n минус n.",
    accent: "#fb7185",
    accentSoft: "#ffe1e7",
    accentStrong: "#c43352",
    background: "linear-gradient(180deg, #ffe7ef 0%, #ffb0c0 42%, #ff6f8e 100%)",
    badge: "×9",
    scenery: ["tower", "stairs"],
    learnCards: [
      {
        title: "Почти десятка",
        text: "9 это 10 минус 1.",
        hint: "Это очень полезный секрет.",
        visual: [makeVisual("▮", [10, -1], "#fb7185")],
      },
      {
        title: "Лестница девяток",
        text: "Ряд: 9, 18, 27, 36.",
        hint: "Смотри, десятки растут, а единицы уменьшаются.",
        visual: [makeVisual("⇡", [9, 18, 27, 36])],
      },
      {
        title: "Выбери этаж",
        text: "Какой ответ у 9 × 4?",
        hint: "Сделай 10 × 4 и убери 4.",
        visual: [makeVisual("▥", [10, 10, 10, 10]), makeVisual("−", [4])],
        interaction: {
          type: "choice",
          prompt: "9 × 4 = ?",
          options: [32, 36, 40],
          correct: 36,
          successText: "Да! 40 минус 4 равно 36.",
        },
      },
      {
        title: "Парные цифры",
        text: "Во многих ответах цифры дают 9: 18, 27, 36, 45.",
        hint: "1+8, 2+7, 3+6.",
        visual: [makeVisual("⌘", [18, 27, 36, 45])],
      },
      {
        title: "Секрет башни",
        text: "Если знаешь десятки, девятки уже не страшны.",
        hint: "Открой объяснение.",
        visual: [makeVisual("✷", [90, -9])],
        interaction: {
          type: "reveal",
          prompt: "Как решить 9 × 7?",
          answer: "Сделай 10 × 7 = 70 и отними 7. Получится 63.",
          buttonLabel: "Показать решение",
        },
      },
    ],
    warmupFactors: [2, 3],
    quizFactors: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
];

export const worldMap = Object.fromEntries(
  worlds.map((world) => [world.multiplier, world]),
) as Record<number, WorldConfig>;
